// Hier kann man Tests durchführen; diese Datei wird nicht kompiliert, wenn dieses Paket als Erweiterung verwendet wird.
Funksteckdosen.auswahlSteckdose(MyEnumFunkgruppen.BOX1)
Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
basic.forever(function () {
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.ON)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.OFF)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.ON)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.ON)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.ON)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.OFF)
    basic.pause(1000)
    Funksteckdosen.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
    basic.pause(1000)
})