// Hier kann man Tests durchführen; diese Datei wird nicht kompiliert, wenn dieses Paket als Erweiterung verwendet wird.
Steckdose.auswahlSteckdose(MyEnumFunkgruppen.BOX1)
Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
basic.forever(function () {
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.ON)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.OFF)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.ON)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.ON)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.ON)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K1, MyEnumState.OFF)
    basic.pause(1000)
    Steckdose.schalteSteckdose(MyEnumSteckdosenNummer.K2, MyEnumState.OFF)
    basic.pause(1000)
})